### ISSUE TITLE
Closed source?

### ISSUE THREAD

**Issue by julianfairfax** [SimpleMobileTools/simplemobiletools.github.io#2]
This repo was last updated 3 years ago, but your website says copyright 2022. I'm assuming the website is now closed source? Why is this now the case? Is it going to be changed?

**Comment by tibbi** [comment]
ye, the website isnt open source

**Comment by PeterDaveHello** [comment]
@tibbi any concerns about open it? I was looking into providing a better version of https://www.simplemobiletools.com/images/button-f-droid.png that been used the README.md files, but can't find the way. Anyway, you may want to use https://gitlab.com/fdroid/artwork/-/raw/master/badge/get-it-on.png or https://gitlab.com/fdroid/artwork/-/raw/master/badge/get-it-on.svg to provide a better look version of it, current one is not so clear.

**Comment by tibbi** [comment]
where do you see f-droid on our website?

**Comment by PeterDaveHello** [comment]
> where do you see f-droid on our website?

As mentioned above, it's on the README files, not on the website.

**Comment by tibbi** [comment]
right, I see what you mean. Anyway, dont you have a .svg file like at Google Play? That would be the best.

**Comment by PeterDaveHello** [comment]
I think the svg URL is also above :sweat_smile:

**Comment by tibbi** [comment]
right, my bad. Remove the padding around it please.

**Comment by PeterDaveHello** [comment]
that's on the f-droid project that I can't directly control, but maybe you can directly crop it?

**Comment by tibbi** [comment]
updated the icons

**Comment by inson1** [comment]
I think it would be better if it would be open source
