### ISSUE TITLE
Two phone buttons to choose from (not sim1 and sim2) 

### ISSUE THREAD

**Issue by JacobKam** [SimpleMobileTools/simplemobiletools.github.io#4]
I downloaded the dialer app. And there is something that is wrong in my opinion. When I choose a number that I want to dial I have to choose between an orange and blue dial button at the bottom of the screen. These are not the sim1 and sim2 buttons. Should there be two buttons? If yes, what is the difference? By the way I have a OnePlus 8t smartphone with last software update (Oxygen 13. 0). Jacob.

**Comment by tibbi** [comment]
what blue and orange? It should be the 2 SIMs.

**Comment by JacobKam** [comment]
Hi, thanks for your message. I sent you two screenshots. In the first screenshot you see sim1 and sim2 before choosing/entering a phone number. Sim1 is chosen. After choosing/entering a phone number I get the screen on the second screenshot with the blue and orange icon. The effect of both buttons is making a sim1 call. So why is there a blue and orange icon? Should they be there on that place? Jacob.

Verzonden met Proton Mail mobiel

-------- Oorspronkelijk bericht --------
Op 11 mrt. 2023 10:53, schreef Tibor Kaputa :

**Comment by tibbi** [comment]
I dont see any screenshots

**Comment by JacobKam** [comment]
No screenshots? I attached two files. I will attached once again.

Verzonden met Proton Mail mobiel

-------- Oorspronkelijk bericht --------
Op 11 mrt. 2023 12:50, schreef Tibor Kaputa :
I dont see any screenshots
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.￼Message ID: ***@***.***>
[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "[https://github.com](<a href=)/SimpleMobileTools/simplemobiletools.github.io/issues/4#issuecomment-1464894339">https://github.com/SimpleMobileTools/simplemobiletools.github.io/issues/4#issuecomment-1464894339", "url": "[https://github.com](<a href=)/SimpleMobileTools/simplemobiletools.github.io/issues/4#issuecomment-1464894339">https://github.com/SimpleMobileTools/simplemobiletools.github.io/issues/4#issuecomment-1464894339", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by JacobKam** [comment]
I wil try it once again with inline screenshots

[Screenshot_2023-03-11-11-11-05-15_765f8dabff0c1b40e2676405b965e035_1.jpg]

[Screenshot_2023-03-11-11-11-33-56_c31b32364ce19ca8fcd150a417ecce58.jpg]e screenshots

Verzonden met [Proton Mail](https://proton.me/) beveiligde e-mail.

------- Original Message -------
Op zaterdag 11 maart 2023 om 12:50 schreef Tibor Kaputa ***@***.***>:

**Comment by tibbi** [comment]
There are no screenshots.. Log into github and add them manually, you are replying somehow through emails that doesnt work well.

**Comment by JacobKam** [comment]
![JacobKam1](https://user-images.githubusercontent.com/127545664/224545665-f97b890f-64d2-4f51-936c-408d0a42557f.jpg)

![JacobKam2](https://user-images.githubusercontent.com/127545664/224545693-1aa1704a-612c-4404-98d7-90c6040d9fe2.jpg)

**Comment by tibbi** [comment]
that orange and blue are 2 separate apps, you can pick which one you want to use for calling
